{{- range .Values.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  password: {{ .secret.password | b64enc }}
  username: {{ .secret.username | b64enc }}
{{- end }}